# Generated by Django 3.2.2 on 2021-05-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210508_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='store_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
