# Generated by Django 3.2.2 on 2021-05-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_store_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='store_link',
        ),
        migrations.RemoveField(
            model_name='account',
            name='temp_otp',
        ),
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
