# Generated by Django 3.2.2 on 2021-05-08 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_address', models.CharField(blank=True, max_length=500, null=True)),
                ('store_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_mrp', models.DecimalField(decimal_places=2, max_digits=18)),
                ('product_sprice', models.DecimalField(decimal_places=2, max_digits=18)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukaan.category')),
            ],
        ),
    ]
