# Generated by Django 3.2.2 on 2021-05-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dukaan', '0003_auto_20210509_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='product_category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_mobile_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_username',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='dukaan.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='store',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='dukaan.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
